name: Ballerina example
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Ballerina Build
        uses: ballerina-platform/ballerina-action@slp2
        with:
          args:
            build -a
