name: Ballerina example
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Ballerina Build
        uses: ballerina-platform/ballerina-action@slp2
        with:
          args:
            build -a
      - name: Ballerina Push
        uses: ballerina-platform/ballerina-action@slp2
        with:
          env: 
            BALLERINA_CENTRAL_ACCESS_TOKEN = ${{ secrets.BallerinaToken }}
          args: 
            push invoice_util
