name: Ballerina example
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Ballerina Build
        uses: ballerina-platform/ballerina-action@master
        with:
          args:
            build -c
      - name: Ballerina Push 
        uses: ballerina-platform/ballerina-action@master 
        env:  
          BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINATOKEN }} 
        with: 
          args:  
            push 